title: Pancham Kotian
logo: /assets/img/headshot_circle.png
email: panchamkotian98@gmail.com
github_username: panchamkotian

description: Electronics Engineer
show_download: true
theme: jekyll-theme-minimal

